### ISSUE TITLE
About how data was proceeded in training script.

### ISSUE THREAD

**Issue by shixiangsong** [HLTCHKUST/UniVaR#2]
Good day!

I'm currently tryting to train the UniVaR based on the Nano contrastors codebase. However, I found that data in your given dataset is separated by languages and models, which confused me on how data is preproceesed in the yaml file. Therefore, I wonder if the yaml of dataset could be released, or how data is preprocessed could be described more clearly in your repo.

Kindly appreciate for your response.

**Comment by ChenDelong1999** [comment]
Hi there, thank you for your interest in our work! We have updated more details about UniVar training implementation, kindly refer to [this page](https://github.com/HLTCHKUST/UniVaR/blob/main/univar_training/README.md) for more information : )

**Comment by shixiangsong** [comment]
Thank you for your code. Good day!
